name: EEL continuous build
on:
  push:
    branches:
      - '*'
      - '!refs/tags/.*'
    tags-ignore:
      - '*'

jobs:
  build:
    name: Build EEL
    runs-on: ubuntu-20.04
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build modified recipe
        run: source cicd/build_recipes.sh
